### ISSUE TITLE
Programmatically create _redirects file through JS objects

### ISSUE THREAD

**Issue by manniL** [nuxt-community/netlify-files-module#4]

**Comment by andre-brdoch** [comment]
@manniL Is there still need for this feature? I'd be willing to make a PR :) 

Also, another netlify file that might be needed is [`netlify.toml`](https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file). For this one, the option to create it programmatically also makes sense.

**Comment by manniL** [comment]
Hey @andre-brdoch 👋🏻

Yes, this feature is still desired 😋

> Also, another netlify file that might be needed is netlify.toml. For this one, the option to create it programmatically also makes sense.

Definitely! Maybe we could focus on netlify.toml in general (instead of _redirects and _headers because they could be "transformed" into a netlify toml).

**Comment by andre-brdoch** [comment]
Hey @manniL, i made a PR 😄 Let me know what you think: https://github.com/nuxt-community/netlify-files-module/pull/11

allowing all 3 types of netlify files to be either copied or created programmatically might still make sense though, even though everything could be done via toml file. However, might get a little messy with the configurations, not sure what would be the best approach.

**Comment by manniL** [comment]
Thanks for the effort! Will check out in the coming days 👍
