### ISSUE TITLE
Why not put files inside /static?

### ISSUE THREAD

**Issue by Bergrebell** [nuxt-community/netlify-files-module#9]
What is the benefit of (currently) using this module instead of just putting the `_redirects` and `_headers` files inside the `/static`-directory?

I can imagine how it could be helpful in the future but currently it doesn't make much sense to me.

**Comment by manniL** [comment]
Because they'd be accessible via /_redirects or /_headers after the deployment

**Comment by Bergrebell** [comment]
makes sense. thanks for the clarification! :)
